2021-08-03 18:22:11,979 __main__         main         coin.py      746 всего аккаунтов
2021-08-03 18:28:08,414 __main__         task         coin.py      {'api:duration': '0.051s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T18:28:08Z', 'api:statuscode': 101}
2021-08-03 18:28:08,432 __main__         task         coin.py      {'api:duration': '0.048s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T18:28:08Z', 'api:statuscode': 101}
2021-08-03 18:28:08,437 __main__         task         coin.py      {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T18:28:08Z', 'api:statuscode': 101, 'api:duration': '0.061s'}
2021-08-03 18:28:08,442 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.045s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T18:28:08Z'}
2021-08-03 18:28:08,443 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.056s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T18:28:08Z'}
2021-08-03 18:28:08,490 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.095s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T18:28:08Z'}
2021-08-03 18:29:25,820 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.029s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T18:29:25Z'}
2021-08-03 18:31:09,033 __main__         main         coin.py      Готово.
2021-08-03 19:22:31,046 __main__         main         coin.py      746 всего аккаунтов
2021-08-03 19:34:52,758 __main__         main         coin.py      Готово.
2021-08-03 20:22:22,617 __main__         main         coin.py      746 всего аккаунтов
2021-08-03 20:25:59,817 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.062s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T20:25:59Z'}
2021-08-03 20:25:59,823 __main__         task         coin.py      {'api:duration': '0.052s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T20:25:59Z', 'api:statuscode': 101}
2021-08-03 20:34:17,673 __main__         main         coin.py      Готово.
2021-08-03 21:22:16,400 __main__         main         coin.py      746 всего аккаунтов
2021-08-03 21:25:15,362 __main__         task         coin.py      {'api:duration': '0.060s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:25:15Z', 'api:statuscode': 101}
2021-08-03 21:25:15,366 __main__         task         coin.py      {'api:timestamp': '2021-08-03T21:25:15Z', 'api:statuscode': 101, 'api:duration': '0.050s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-03 21:25:15,575 __main__         task         coin.py      {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:25:15Z', 'api:statuscode': 101, 'api:duration': '0.199s'}
2021-08-03 21:28:26,464 __main__         task         coin.py      {'api:duration': '0.056s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:28:26Z', 'api:statuscode': 101}
2021-08-03 21:28:26,467 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.053s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:28:26Z'}
2021-08-03 21:28:26,473 __main__         task         coin.py      {'api:duration': '0.062s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:28:26Z', 'api:statuscode': 101}
2021-08-03 21:30:44,201 __main__         task         coin.py      {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:30:44Z', 'api:statuscode': 101, 'api:duration': '0.036s'}
2021-08-03 21:30:44,235 __main__         task         coin.py      {'api:duration': '0.075s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:30:44Z', 'api:statuscode': 101}
2021-08-03 21:33:08,174 __main__         task         coin.py      {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101, 'api:duration': '0.053s'}
2021-08-03 21:33:08,182 __main__         task         coin.py      {'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101, 'api:duration': '0.051s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-03 21:33:08,179 __main__         task         coin.py      {'api:duration': '0.051s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101}
2021-08-03 21:33:08,193 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.091s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z'}
2021-08-03 21:33:08,198 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.084s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z'}
2021-08-03 21:33:08,215 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.087s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z'}
2021-08-03 21:33:08,230 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.108s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z'}
2021-08-03 21:33:08,245 __main__         task         coin.py      {'api:duration': '0.113s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101}
2021-08-03 21:33:08,284 __main__         task         coin.py      {'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101, 'api:duration': '0.151s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-03 21:33:08,339 __main__         task         coin.py      {'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101, 'api:duration': '0.204s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-03 21:33:08,377 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.241s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z'}
2021-08-03 21:33:08,437 __main__         task         coin.py      {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101, 'api:duration': '0.298s'}
2021-08-03 21:33:08,519 __main__         task         coin.py      {'api:statuscode': 101, 'api:duration': '0.381s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z'}
2021-08-03 21:33:08,528 __main__         task         coin.py      {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101, 'api:duration': '0.390s'}
2021-08-03 21:33:08,577 __main__         task         coin.py      {'api:duration': '0.435s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101}
2021-08-03 21:33:08,637 __main__         task         coin.py      {'api:duration': '0.499s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T21:33:08Z', 'api:statuscode': 101}
2021-08-03 21:34:48,744 __main__         main         coin.py      Готово.
2021-08-03 22:22:20,563 __main__         main         coin.py      746 всего аккаунтов
2021-08-03 22:23:02,132 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.033s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:23:02Z'}
2021-08-03 22:23:02,144 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.029s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:23:02Z'}
2021-08-03 22:23:02,148 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.046s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:23:02Z'}
2021-08-03 22:23:02,203 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:23:02Z', 'api:statuscode': 101, 'api:duration': '0.020s'}
2021-08-03 22:23:02,220 __main__         task         coin.py      Task Exception {'api:duration': '0.026s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:23:02Z', 'api:statuscode': 101}
2021-08-03 22:30:54,148 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.029s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:30:54Z'}
2021-08-03 22:30:54,153 __main__         task         coin.py      Task Exception {'api:duration': '0.034s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:30:54Z', 'api:statuscode': 101}
2021-08-03 22:30:54,160 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.040s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:30:54Z'}
2021-08-03 22:30:54,189 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.079s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:30:54Z'}
2021-08-03 22:30:54,713 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-03T22:30:54Z', 'api:statuscode': 101, 'api:duration': '0.572s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-03 22:30:54,732 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.573s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-03T22:30:54Z'}
2021-08-03 22:34:50,789 __main__         main         coin.py      Готово.
2021-08-04 00:22:24,643 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 00:26:26,423 __main__         task         coin.py      Task Exception Expecting value: line 1 column 1 (char 0)
2021-08-04 00:34:55,700 __main__         main         coin.py      Готово.
2021-08-04 01:22:28,108 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 01:35:01,875 __main__         main         coin.py      Готово.
2021-08-04 02:22:26,663 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 02:27:09,621 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.069s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T02:27:09Z'}
2021-08-04 02:27:09,629 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T02:27:09Z', 'api:statuscode': 101, 'api:duration': '0.082s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 02:27:09,634 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T02:27:09Z', 'api:statuscode': 101, 'api:duration': '0.089s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 02:27:09,641 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T02:27:09Z', 'api:statuscode': 101, 'api:duration': '0.093s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 02:27:09,645 __main__         task         coin.py      Task Exception {'api:duration': '0.076s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T02:27:09Z', 'api:statuscode': 101}
2021-08-04 02:27:09,740 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T02:27:09Z', 'api:statuscode': 101, 'api:duration': '0.142s'}
2021-08-04 02:34:53,546 __main__         main         coin.py      Готово.
2021-08-04 03:22:22,162 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 03:34:54,725 __main__         main         coin.py      Готово.
2021-08-04 04:22:22,014 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 04:34:53,528 __main__         main         coin.py      Готово.
2021-08-04 05:22:28,004 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 05:35:05,451 __main__         main         coin.py      Готово.
2021-08-04 06:22:33,093 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 06:30:25,854 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T06:30:25Z', 'api:statuscode': 101, 'api:duration': '0.050s'}
2021-08-04 06:30:25,865 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T06:30:25Z', 'api:statuscode': 101, 'api:duration': '0.062s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 06:30:25,868 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.061s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T06:30:25Z'}
2021-08-04 06:30:25,872 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.045s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T06:30:25Z'}
2021-08-04 06:30:25,942 __main__         task         coin.py      Task Exception {'api:duration': '0.109s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T06:30:25Z', 'api:statuscode': 101}
2021-08-04 06:31:30,249 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T06:31:30Z', 'api:statuscode': 101, 'api:duration': '0.061s'}
2021-08-04 06:31:30,289 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T06:31:30Z', 'api:statuscode': 101, 'api:duration': '0.048s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 06:31:30,296 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T06:31:30Z', 'api:statuscode': 101, 'api:duration': '0.034s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 06:31:30,333 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.035s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T06:31:30Z'}
2021-08-04 06:31:30,335 __main__         task         coin.py      Task Exception {'api:duration': '0.042s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T06:31:30Z', 'api:statuscode': 101}
2021-08-04 06:31:30,347 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T06:31:30Z', 'api:statuscode': 101, 'api:duration': '0.029s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 06:35:03,301 __main__         main         coin.py      Готово.
2021-08-04 07:22:25,543 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 07:35:20,427 __main__         main         coin.py      Готово.
2021-08-04 08:22:38,045 __main__         main         coin.py      746 всего аккаунтов
2021-08-04 08:23:53,234 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T08:23:52Z', 'api:statuscode': 101, 'api:duration': '0.074s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 08:23:53,268 __main__         task         coin.py      Task Exception {'api:duration': '0.047s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:23:52Z', 'api:statuscode': 101}
2021-08-04 08:24:47,303 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T08:24:46Z', 'api:statuscode': 101, 'api:duration': '0.027s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 08:24:47,315 __main__         task         coin.py      Task Exception {'api:duration': '0.046s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:24:46Z', 'api:statuscode': 101}
2021-08-04 08:24:47,316 __main__         task         coin.py      Task Exception {'api:duration': '0.025s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:24:46Z', 'api:statuscode': 101}
2021-08-04 08:24:47,318 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:24:46Z', 'api:statuscode': 101, 'api:duration': '0.041s'}
2021-08-04 08:24:47,875 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.617s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:24:47Z'}
2021-08-04 08:25:00,896 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.029s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:25:00Z'}
2021-08-04 08:25:00,921 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:25:00Z', 'api:statuscode': 101, 'api:duration': '0.034s'}
2021-08-04 08:25:00,924 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.036s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:25:00Z'}
2021-08-04 08:25:00,917 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T08:25:00Z', 'api:statuscode': 101, 'api:duration': '0.033s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 08:27:26,191 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:27:25Z', 'api:statuscode': 101, 'api:duration': '0.067s'}
2021-08-04 08:27:36,943 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.032s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:27:36Z'}
2021-08-04 08:27:36,988 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.073s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:27:36Z'}
2021-08-04 08:27:37,005 __main__         task         coin.py      Task Exception {'api:duration': '0.018s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:27:36Z', 'api:statuscode': 101}
2021-08-04 08:29:46,676 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T08:29:45Z', 'api:statuscode': 101, 'api:duration': '0.027s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 08:29:46,684 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:29:45Z', 'api:statuscode': 101, 'api:duration': '0.022s'}
2021-08-04 08:29:46,692 __main__         task         coin.py      Task Exception {'api:duration': '0.045s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:29:45Z', 'api:statuscode': 101}
2021-08-04 08:29:47,284 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T08:29:46Z', 'api:statuscode': 101, 'api:duration': '0.017s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 08:29:47,294 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.026s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:29:46Z'}
2021-08-04 08:29:47,299 __main__         task         coin.py      Task Exception {'api:duration': '0.023s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:29:46Z', 'api:statuscode': 101}
2021-08-04 08:29:47,303 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.037s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:29:46Z'}
2021-08-04 08:29:47,325 __main__         task         coin.py      Task Exception {'api:duration': '0.023s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:29:46Z', 'api:statuscode': 101}
2021-08-04 08:30:49,194 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.034s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:30:48Z'}
2021-08-04 08:30:49,302 __main__         task         coin.py      Task Exception {'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:30:48Z', 'api:statuscode': 101, 'api:duration': '0.036s'}
2021-08-04 08:30:55,378 __main__         task         coin.py      Task Exception {'api:duration': '0.029s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:30:54Z', 'api:statuscode': 101}
2021-08-04 08:30:55,433 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.100s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:30:54Z'}
2021-08-04 08:30:55,489 __main__         task         coin.py      Task Exception {'api:timestamp': '2021-08-04T08:30:54Z', 'api:statuscode': 101, 'api:duration': '0.131s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.'}
2021-08-04 08:30:55,518 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.124s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:30:54Z'}
2021-08-04 08:30:55,552 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.170s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:30:54Z'}
2021-08-04 08:30:55,663 __main__         task         coin.py      Task Exception {'api:duration': '0.220s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:30:54Z', 'api:statuscode': 101}
2021-08-04 08:34:26,128 __main__         task         coin.py      Task Exception {'api:statuscode': 101, 'api:duration': '0.068s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:34:25Z'}
2021-08-04 08:34:26,288 __main__         task         coin.py      Task Exception {'api:duration': '0.109s', 'api:message': 'Oops... Internal server error. We are fixing this problem now. If this error continues, please contact us.', 'api:timestamp': '2021-08-04T08:34:25Z', 'api:statuscode': 101}
2021-08-04 08:35:21,261 __main__         main         coin.py      Готово. 746
